version: '3.8'

services:
  pdf2ocr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      # Optional: set an API key to protect the webhook. If unset, no API key is required.
      - API_KEY=${API_KEY:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:5000/health\")' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3