version: '3.8'

services:
  pdf2ocr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      # Optional: set an API key to protect the webhook. If unset, no API key is required.
      - API_KEY=${API_KEY:-}